# Generated by Django 4.0.4 on 2022-05-28 18:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gallary', '0002_alter_category_description_alter_image_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallary.category'),
        ),
        migrations.AlterField(
            model_name='image',
            name='description',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='image',
            name='location',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='gallary.location'),
        ),
        migrations.AlterField(
            model_name='location',
            name='Description',
            field=models.TextField(),
        ),
    ]
